### ISSUE TITLE
release 1.0.0

### ISSUE THREAD

**Issue by ApayRus** [Aparus/ulla#4]
- [x] #1 custom beautifull drawer
- [x] #2 parse markdown to js object
- [x] #3 node script to make assets map (audios and images)
- [x] #5 global styles related to language
- [x]  #7 universal file structure

**Comment by ApayRus** [comment]
release published 25 October 2020
